name: Upload PR Build Scans - Maven

on:
  workflow_run:
    workflows: [ "PR Build - Maven" ]
    types: [ completed ]
  issue_comment:
    types: [ created ]

jobs:

  publish-build-scans:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      actions: write
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Setup Build Scan link capture
        uses: gradle/github-actions/maven-setup@v0.0.1
        with:
          skip-non-republished-builds-in-job-summary: true
      - name: Publish Build Scans
        uses: gradle/github-actions/maven-publish-build-scan@v0.0.1
        with:
          develocity-url: 'https://ge.solutions-team.gradle.com'
          develocity-access-key: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}
          skip-comment: false
          skip-project-detail: false
          authorized-list: ''
      - name: Debug
        run: |
          if [ -f /home/runner/work/_temp/maven-build-scan-data/build-metadata.json ]; then jq '.' /home/runner/work/_temp/maven-build-scan-data/build-metadata.json >> $GITHUB_STEP_SUMMARY; fi
